spring:
  datasource:
    masterUrl: jdbc:mysql://localhost:3306/boot-tutu-mall?useUnicode=true&serverTimezone=UTC
    slaveUrl: jdbc:mysql://localhost:3307/boot-tutu-mall?useUnicode=true&serverTimezone=UTC
    username: root
    password: 990712
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    #数据源其他配置

    # 初始化连接池的大小
    initialSize: 5
    # 连接池中的最小空闲连接数
    minIdle: 5
    # 连接池中的最大的连接数
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 验证数据库连接的查询语句
    validationQuery: SELECT 1 FROM DUAL
    # 获取连接的时候测试连接的有效性
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 是否缓存preparedStatement，
    poolPreparedStatements: true
    # 配置监控统计拦截的filters,去掉后监控界面sql无法统计, wall用于防火墙
    filters: stat,wall,log4j2
    maxPoolPreparedStatementPerConnectionSize: 20
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能;慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # 设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    properties:
      hibernate: true
  redis:
    host: 119.29.35.129
    port: 6379
    pool:
      # 控制一个pool可分配多少个jedis实例
      maxActive: 100
      #  连接池中最多可空闲maxIdle个连接 这里取值为20 表示即使没有数据库连接时依然可以保持20空闲的连接
      maxIdle: 20
      # 最大等待时间:当没有可用连接时,连接池等待连接被归还的最大时间(以毫秒计数),超过时间则抛出异常
      maxWait: 3000
    timeout: 3000
    password: 990712
  #    schema:
  #     - classpath:backup.sql
  mvc:
    view:
      prefix: /html/
      suffix: .html
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  #配置包别名
  type-aliases-package: cn.qingweico.entity
  config-location: classpath:/mybatis-config.xml
server:
  port: 80
pic:
  path:
    windows: "E:/picture"
    linux: "/home/image"
    shop: "/upload/item/shop/"
    headline: "/upload/item/head-title/"
    shopCategory: "/upload/item/shop-category/"
    user: "/upload/item/user/"

#微信相关
wechat:
  appid: wxdb083dcc9aa17973
  appsecret: ad949e76afa540e0245a4422248515e8
  prefix: https://open.weixin.qq.com/connect/oauth2/authorize?appid=${wechat.appid}&redirect_uri=
  middle: "&response_type=code&scope=snsapi_userinfo&state="
  suffix: "#wechat_redirect"
  auth.url: http://mall.qingweico.cn/shopadmin/addshopauthmap
  login.url: http://mall:qingweico.cn/wechatlogin/logincheck
  exchange.url: http://mall.qingweico.cn/shopadmin/exchangeaward
  productmap.url: http://mall.qingweico.cn/shopadmin/adduserproductmap